application: discipline-score
version: 4
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: todoapp.py

builtins:
- remote_api: on
